language: android

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
    - build-tools-27.0.1
    - android-27
  licenses:
    - 'android-sdk-license-.+'

notifications:
    # travis update notifications for email on success and on failure
    email:
      recipients:
        - sophiaquach16@gmail.com
        - jadmalek92@gmail.com
        - amawai.731@gmail.com
        - mnhn329@gmail.com
        - pxaman@gmail.com
        - roger_lu_dude@hotmail.com
        - artemmikhalitsin@gmail.com
      on_success: always
      on_failure: always

jobs:
  # note that the reason for the no language set is an issue with the beta version of the build stages
  # for the android language
  include:
    # will compile build the app's dependencies
    - stage: compile
      language: android
      script: ./gradlew -q app:dependencies --configuration compile
    # will run all tests of the application
    - stage: All Tests
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew testDevDebug
    # will build the release 1 tests added by our team
    - stage: Release 1 Tests
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew -p app/src/test/java/org/wikipedia/feed/onthisday
      script: ./gradlew -p app/src/test/java/org/wikipedia/activity
      script: ./gradlew -p app/src/test/java/org/wikipedia/settings
    # will build the release 2 tests added by our team
    - stage: Release 2 Tests
      language: android
      script: ./gradlew -p app/src/test/java/org/wikipedia/travel
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/espresso/travel
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/travel
      # will build the release 3 tests added by our team
    - stage: Release 3 Tests
      language: android
      script: ./gradlew -p app/src/test/java/org/wikipedia/translation
      script: ./gradlew -p app/src/test/java/org/wikipedia/search
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/page
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/espresso/privateBrowsing
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/espresso/articleNote
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/espresso/translation
    # will inspect deploy build without skipping on tagged commits for releases
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: "e8c08bbdb7fef2959553f8eb8c2f376135b9ab33"
        skip_cleanup: true
        on:
          tags: true