language: android

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
    - build-tools-27.0.1
    - android-27
  licenses:
    - 'android-sdk-license-.+'

jobs:
  # note that the reason for the no language set is an issue with the beta version of the build stages
  # for the android language
  include:
    # will compile build the app's dependencies
    - stage: compile
      language: android
      script: ./gradlew -q app:dependencies --configuration compile
    # will run all tests of the application
    - stage: All Tests
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew testDevDebug
    # will build the release 1 tests added by our team
    - stage: Release 1 Tests
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew -p app/src/test/java/org/wikipedia/feed/onthisday
      script: ./gradlew -p app/src/test/java/org/wikipedia/activity
      script: ./gradlew -p app/src/test/java/org/wikipedia/settings
    # will build the release 2 tests added by our team
    - stage: Release 2 Tests
      language: android
      script: ./gradlew -p app/src/test/java/org/wikipedia/travel
    # will inspect deploy build without skipping on tagged commits for releases
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true