language: android

env:
# CODACY_PROJECT_TOKEN token
  - secure: "OZh/LwaukUtuyPO477tzN+6E3RR2GljUR3V74wyTVYuBSMkwDv0kX5eHOd08kkWnq/JnCAb8Nq9QwyUHPPotpwnjxbcBnPMiMP9AIuWYr0IeCCdoJswwnZSt1dX0GLVLnJE6hEDMIb+ULxNGsxLZNlCa5xmODiYfSCndLByEqoh6IwaDjDxlW5qwTXXFmW4S8rzoTDgYMuiJeNyqqcAT59ZHpos79tYL4odTMRoFtxn/cxPBwQy7yI4zgkfFJHOEjAdQgpkMMQ2iYSbm0kk+IEPRnk6tiDfv6DmXkbQ3x0osVndJ9EFgLCLsm/uWblrJC2q+bJTOa7xc022HarKQxTQc868rvCMKeRTpY1nYf3W923m9vNLUmiKs9De5+i56/7/5P4YXLTBjW9p/7u35/4y4CIe6isi1rwmw+K7qVnt/ngQTAl6/fI35jTKUu0xhN6btmY8IxzPOFbdp+ZyW1VXZMLsPFeE+C4yQLyKs9kDy4k5KC3v51kQKlVZy6DYusfaGYaw50z3rYfeWYh4EOWEF3t7MY3sxMSNjR/Yjb1dfW+/0FmfGmJt0waGcwIG/HEGoyytzOUi0RxhcxieVeNAmxRzEHu46aSm9+SJg9+8KRd4X5Z+jaGtedmlux3cpFLF++/M+RjlrbWlXNy75n/Jb3KYGpckojNuoQ4O2quM="

before_install:
  - yes | sdkmanager "platforms;android-27"
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

android:
  components:
    - build-tools-27.0.1
    - android-27
  licenses:
    - 'android-sdk-license-.+'

jdk:
    - oraclejdk8

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

notifications:
    # travis update notifications for email on success and on failure
    email:
      recipients:
        - sophiaquach16@gmail.com
        - jadmalek92@gmail.com
        - amawai.731@gmail.com
        - mnhn329@gmail.com
        - pxaman@gmail.com
        - roger_lu_dude@hotmail.com
        - artemmikhalitsin@gmail.com
      on_success: always
      on_failure: always

jobs:
  # note that the reason for the no language set is an issue with the beta version of the build stages
  # for the android language
  include:
    # will compile build the app's dependencies
    - stage: compile
      language: android
      script: ./gradlew -q app:dependencies --configuration compile
    # will run all tests of the application
    - stage: All Tests
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew testDevDebug
    # will build the release 1 tests added by our team
    - stage: Release 1 Tests
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew -p app/src/test/java/org/wikipedia/feed/onthisday
      script: ./gradlew -p app/src/test/java/org/wikipedia/activity
      script: ./gradlew -p app/src/test/java/org/wikipedia/settings
    # will build the release 2 tests added by our team
    - stage: Release 2 Tests
      language: android
      script: ./gradlew -p app/src/test/java/org/wikipedia/travel
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/espresso/travel
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/travel
      # will build the release 3 tests added by our team
    - stage: Release 3 Tests
      language: android
      script: ./gradlew -p app/src/test/java/org/wikipedia/translation
      script: ./gradlew -p app/src/test/java/org/wikipedia/search
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/page
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/espresso/privateBrowsing
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/espresso/articleNote
      script: ./gradlew -p app/src/androidTest/java/org/wikipedia/espresso/translation
    # will inspect deploy build without skipping on tagged commits for releases
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: "e8c08bbdb7fef2959553f8eb8c2f376135b9ab33"
        skip_cleanup: true
        on:
          tags: true