language: android

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
    - build-tools-27.0.1
    - android-27
  licenses:
    - 'android-sdk-license-.+'

jobs:
  include:
    # will compile build the app's dependencies
    - stage: compile
      language: android
      script: ./gradlew -q app:dependencies --configuration compile
    # will run all tests of the application
    - stage: test
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew testDevDebug
    # will inspect deploy build without skipping on tagged commits for releases
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true